// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/feature/Exercise/data/data_source/remote/exercise_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/network/common/api_result.dart' as _i6;
import 'package:fitness_app/core/network/remote/api_manager.dart' as _i5;
import 'package:fitness_app/feature/Exercise/data/api/exercise_retrofit.dart'
    as _i3;
import 'package:fitness_app/feature/Exercise/data/data_source/local/exercise_local_data_source.dart'
    as _i8;
import 'package:fitness_app/feature/Exercise/data/model/exercise_model.dart'
    as _i9;
import 'package:fitness_app/feature/Exercise/data/model/exercise_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExerciseListResponseModel_0 extends _i1.SmartFake
    implements _i2.ExerciseListResponseModel {
  _FakeExerciseListResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRetrofitClient extends _i1.Mock
    implements _i3.ExerciseRetrofitClient {
  MockExerciseRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExerciseListResponseModel> getExercises(
    String? muscleId,
    String? difficultyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercises, [muscleId, difficultyId]),
            returnValue: _i4.Future<_i2.ExerciseListResponseModel>.value(
              _FakeExerciseListResponseModel_0(
                this,
                Invocation.method(#getExercises, [muscleId, difficultyId]),
              ),
            ),
          )
          as _i4.Future<_i2.ExerciseListResponseModel>);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i5.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.Result<T>> execute<T>(_i4.Future<T> Function()? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiCall]),
            returnValue: _i4.Future<_i6.Result<T>>.value(
              _i7.dummyValue<_i6.Result<T>>(
                this,
                Invocation.method(#execute, [apiCall]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<T>>);
}

/// A class which mocks [ExerciseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLocalDataSource extends _i1.Mock
    implements _i8.ExerciseLocalDataSource {
  MockExerciseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheExercises(
    List<_i9.ExerciseModel>? exercises,
    String? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheExercises, [exercises, key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.ExerciseModel>> getCachedExercises(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedExercises, [key]),
            returnValue: _i4.Future<List<_i9.ExerciseModel>>.value(
              <_i9.ExerciseModel>[],
            ),
          )
          as _i4.Future<List<_i9.ExerciseModel>>);
}
